### ISSUE TITLE
fatal errror occured could not locate linux data

### ISSUE THREAD

**Issue by wilbolinux** [Tomas-M/linux-live#27]
if i start the live build linux distro...

Problem:

...fatal errror occured could not locate linux data

it didnt work ...

...where they located ?

**Comment by Tomas-M** [comment]
It tries to find data in /linux/ directory (unless you renamed LIVEKITNAME in config file).
It mounts all visible hard drives and USB drives in your computer and tries to find such directory.

**Comment by Lucapz** [comment]
We could do with a linux-live forum so we can help each other out with this type of thing.

Even if it only had one section it would be better than nothing.

**Comment by Lucapz** [comment]
@Tomas-M 

Full install of Debian Sid including all my applications and drivers compressed to 1.1gb which is impressive. :) 👍 

Though of the Zip and ISO install i could only get Zip to work on a Fat32 USB drive which worked perfectly , everything else either gave a boot error.

ISO with any writer including direct with DD gave a boot error please press key to continue

EXT4 stopped at syslinux  and NTFS gave an error at INIT that it couldn't find  a /LINUX folder the same as  wilbolinux pointed out.

So at least FAT32 works and i'm impressed with it , thank you for your script :)

**Comment by Lucapz** [comment]
@Tomas-M 

I see you have added a mailing list but they are not as easy to use a standard forum.

Devuan / Refracta have been given their own section on the unofficial debianuserforums

http://www.debianuserforums.org/viewforum.php?f=65

Seeing as Slax is now based on Debian could you not request your own section on there so people can get general Debian help along with Slax and being hosted by someone else you don't need to maintain anything?

Thanks

**Comment by Lucapz** [comment]
@Tomas-M 

The linux live script has now named everything Slax and the bootinst now gives an error on a FAT32 drive.

bootinst.sh: 18: bootinst.sh: ./extlinux.x64: Permission denied Error installing boot loader.

Read the errors above and press enter to exit...

**Comment by Tomas-M** [comment]
I am such an idiot.
Sorry

I forgot 'slax' there. It's fixed in git now.

If you get permission denied, that is strange. Did you start it as root?
Anyway, you'll need to download and run it once more again, sorry for that.


Tomas M

**Comment by Lucapz** [comment]
It's now named correctly but i still have the permission denied error.

I'm not doing anything different from previous script builds and it's in root on the same drive and computer i've always used.

**Comment by Tomas-M** [comment]
Can you run extlinux.x64 manually? Can  you run any other binary from the same partition/drive? Maybe it is mounted in a way which forbids execution...

**Comment by Lucapz** [comment]
@Tomas-M 

Only thing that has been changed is updating to the latest script and things are now getting messy that it's beyond my technical skills to proceed. :(

With the latest i now get this verbose at 99% of the build that i never had before.
>File /var/log/daemon.log changed size while reading filesystem, attempting to re-read

bootinst.sh still doesn't work with FAT32 but works on EXT4 and NTFS but it then spits out loads of AUfs/Union and fstab errors at boot with a message that this shouldn't happen.

**Comment by Tomas-M** [comment]
I'd recommend to start over from the beginning :)

**Comment by Lucapz** [comment]
This is from the beginning of the ./build on a virgin install of Debian 9 and i've started from a fresh each time for FAT32 ,NTFS and EXT4 tests.

Everything worked before you started adding ntfs-3g support and now sadly it's currently unusable. :(

As i say i've only updated the script as you have made changes and i never had any fstab errors until yesterday when you added the nofail Commits.

**Comment by Tomas-M** [comment]
It is hard for me to track down problems if people keep replying to previous issues.
You can try the latest release tag https://github.com/Tomas-M/linux-live/releases/tag/v2.1 
which does not include the latest changes.

Please open a new issue if you have any new troubles. Thank you.

**Comment by Tomas-M** [comment]
Alternatively you can test current master, I was able to track down my error so lets hope this time it works.
